// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQlBA9F5laZqMQHUXnHni3LK2K5AzzpVY',
    appId: '1:161178314752:web:04e0c0cfe16aa454d6d0e5',
    messagingSenderId: '161178314752',
    projectId: 'ecommerceapp-2e2d9',
    authDomain: 'ecommerceapp-2e2d9.firebaseapp.com',
    storageBucket: 'ecommerceapp-2e2d9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADK7J1EGxnpkeBKVHjitWGxX_ukMr8g5k',
    appId: '1:1096906187223:android:205694715977eddf7a2b92',
    messagingSenderId: '1096906187223',
    projectId: 'pomme-dapi-d7b1d',
    storageBucket: 'pomme-dapi-d7b1d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZB2cyyQKqLoxI2jpRY379vMNN7dNtqnU',
    appId: '1:1096906187223:ios:c7ad0c0e0baadc867a2b92',
    messagingSenderId: '1096906187223',
    projectId: 'pomme-dapi-d7b1d',
    storageBucket: 'pomme-dapi-d7b1d.firebasestorage.app',
    iosBundleId: 'com.example.pommeDapi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQlBA9F5laZqMQHUXnHni3LK2K5AzzpVY',
    appId: '1:161178314752:web:7d146b5cd83b61c9d6d0e5',
    messagingSenderId: '161178314752',
    projectId: 'ecommerceapp-2e2d9',
    authDomain: 'ecommerceapp-2e2d9.firebaseapp.com',
    storageBucket: 'ecommerceapp-2e2d9.appspot.com',
  );

}